### PR TITLE
v7: add NewSnapshot function

### PR DESCRIPTION
**Pull request by rogpeppe**
### Describe the purpose of your pull request

This makes it straightforward to create a snapshot that holds a known
set of values (for testing, for example).

Also in passing, change the log message printed when
a flag's value is returned to include the flag's name,
which makes the message more useful.

### Requirement checklist (only if applicable)

- [x] I have covered the applied changes with automated tests.
- [x] I have executed the full automated test set against my changes.
- [ ] I have validated my changes against all supported platform versions.
- [x] I have read and accepted the [contribution agreement](https://github.com/configcat/legal/blob/main/contribution-agreement.md).

### CODE REVIEW

**Review by z4kn4fein — APPROVED** [review]
Hi @rogpeppe,

Thanks for the PR! I think this feature is great, we also have plans to put a local configuration option in our SDKs later and this is something that we definitely could use as a first step in this SDK.

**Comment by rogpeppe** [comment]
> Thanks for the PR! I think this feature is great, we also have plans to put a local configuration option in our SDKs later and this is something that we definitely could use as a first step in this SDK.

Glad you like it. :) BTW I have a PR after this that makes this quite a bit more efficient (it's a little bit more intrusive than this, so I thought it would be better to land this first).

**Comment by rogpeppe** [comment]
I just proposed the other PR: https://github.com/configcat/go-sdk/pull/41

You might prefer to just land that one and abandon this.

**Comment by rogpeppe** [comment]
Superceded by #41

**Pull request closed without merging**
